services:
  - type: web
    name: sql-runner-backend
    env: python
    rootDir: .
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn backend.sqlrunner.wsgi:application"
    plan: free
